name: Build and deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd ./mystmd-docker
          docker build -o ./mystmd -t gongzhq/mystmd . && tar -czf mystmd_latest.tar.gz mystmd

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{github.ref}}
          draft: false
          prerelease: false

      - name: Upload Docker image to release
        uses: actions/upload-artifact@v4
        with:
          name: mystmd-docker
          path: mystmd_latest.tar.gz
