name: Build and deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd ./mystmd-docker
          docker build -t gongzhq/mystmd .

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag: "v${DATE}"
          release-name: "Release ${DATE}"
          draft: false
          prerelease: false
          files: |
            docker-image.tar.gz

      - name: Upload Docker image to release
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: docker-image.tar.gz
